defaults:
  - _self_
  - problem: logistic_LISR_k
  - llm_client: openai
  - override hydra/output: local

hydra:
  job:
    name: ${problem.problem_name}-${problem.problem_type}
    chdir: True

# The chosen algorithm
algorithm: reevo2d # other options are "eoh", "ael"; some problems may not support "ael"   # reevo2d
reevo_func_index: [3] # other options are "eoh", "ael"; some problems may not support "ael"   # reevo2d

# Main GA loop parameters
max_fe: 5000 # 1000 # maximum number of function evaluations
pop_size: 50 # 50 # population size for GA
init_pop_size: 200 # 200 # initial population size for GA
mutation_rate: 0.8 # mutation rate for GA
timeout: 300 # timeout for evaluation of a single heuristic
diversify_init_pop: True # whether to diversify the initial population

model: deepseek-coder # LLM model
temperature: 0.5  # temperature for chat completion

